markdown:  rdiscount
permalink: /:year/:month/:day/:title
title:     UnQLite
url:       http://unqlite.github.io
exclude:   [ README.md sitemap.xml robots.txt atom.xml ]
author:    unqlite
email:     unqlite@gmail.com
pygments:  true
paginate:  3
auto:      false

